[tool.poetry]
name = "nonebot-adapter-feishu"
version = "2.0.0-alpha.16"
description = "feishu(larksuite) adapter for nonebot2"
authors = ["StarHeartHunt <starheart233@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://v2.nonebot.dev/"
repository = "https://github.com/nonebot/nonebot2"
documentation = "https://v2.nonebot.dev/"
keywords = ["bot", "qq", "qqbot", "feishu", "larksuite"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Framework :: Robot Framework",
  "Framework :: Robot Framework :: Library",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3"
]
packages = [
  { include = "nonebot" }
]
exclude = ["nonebot/__init__.py", "nonebot/adapters/__init__.py"]

[tool.poetry.dependencies]
python = "^3.7.3"
aiocache = "^0.11.1"
pycryptodome = "^3.10.1"
httpx = ">=0.18.0, <1.0.0"
nonebot2 = "^2.0.0-alpha.14"

[tool.poetry.dev-dependencies]
nonebot2 = { path = "../../", develop = true }

# [[tool.poetry.source]]
# name = "aliyun"
# url = "https://mirrors.aliyun.com/pypi/simple/"
# default = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
