[tool.poetry]
name = "nonebot-plugin-docs"
version = "2.0.0-alpha.11"
description = "View NoneBot2 Docs Locally"
authors = ["yanyongyu <yyy@nonebot.dev>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/nonebot/nonebot2/blob/master/packages/nonebot-plugin-docs"
repository = "https://github.com/nonebot/nonebot2"
keywords = ["nonebot", "nonebot2", "docs"]
include = ["nonebot_plugin_docs/dist/**/*"]


[tool.poetry.dependencies]
python = "^3.7"
nonebot2 = "^2.0.0-alpha.1"
aiofiles = "^0.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
