name: Code Coverage

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "envs/**"
      - "nonebot/**"
      - "packages/**"
      - "tests/**"
      - ".github/actions/setup-python/**"
      - ".github/workflows/codecov.yml"
      - "pyproject.toml"
      - "poetry.lock"

jobs:
  test:
    name: Test Coverage
    runs-on: ${{ matrix.os }}
    concurrency:
      group: test-coverage-${{ github.ref }}-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.env }}
      cancel-in-progress: true
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]
        env: [pydantic-v1, pydantic-v2]
      fail-fast: false
    env:
      OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}
      PYDANTIC_VERSION: ${{ matrix.env }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}
          env-dir: ./envs/${{ matrix.env }}
          no-root: true

      - name: Run Pytest
        run: |
          cd ./envs/${{ matrix.env }}
          poetry run bash "../../scripts/run-tests.sh"

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          env_vars: OS,PYTHON_VERSION,PYDANTIC_VERSION
          files: ./tests/coverage.xml
          flags: unittests
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
